name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 21.5.0

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Application
        run: cd client && npm i -g pnpm@latest && pnpm && pnpm lint

  type-check:
    name: Types
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Application Types
        run: cd client && npm i -g pnpm@latest && pnpm && pnpm type-check
        
  prettify:
    name: Prettier
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Check Application Types
        run: cd client && npm i -g pnpm@latest && pnpm && pnpm prettier:fix
